# Generated by Django 5.1.5 on 2025-01-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_id', models.CharField(max_length=50, unique=True)),
                ('contract_data', models.JSONField()),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
